spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: users
    password: users
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    queue: user_registered
    exchange: users.exchange
    routingKey: user_registered
    bindingKeyPattern: user.*

logging:
  level:
    root: INFO
